apps/carrinhos/urls.py
from django.urls import path

from apps.carrinhos.views import *

app_name = 'pedidos'

urlpatterns = [
     path('visualizar-carrinho/', visualizar_carrinho, name='visualizar_carrinho'),
     path('adicionar-produto-carrinho/', adicionar_produto_carrinho, name='adicionar_produto_carrinho'),
     path('listar-pedidos/', listar_pedidos, name='listar_pedidos'),
     path(
        'pedido/<int:pk_pedido>/pedido-produto/<int:pk_pedido_produto>/visualizar-produto/<str:nome_produto>/<int:pk_produto>/',
        visualizar_produto_pedido, name='visualizar_produto_pedido'
    ),
     path('ajax/remover-produto-pedido/', remover_produto_pedido, name='remover_produto_pedido'),
     path('ajax/alterar-quantidade-produto-pedido/', alterar_quantidade_produto_pedido, name='alterar_quantidade_produto_pedido'),
]

apps/empresas/urls.py
from django.urls import path

from .views.empresa import *
from .views import endereco
from .views import empresa

app_name = 'empresas'

urlpatterns = [
    path('criar-empresa/', CriarEmpresa.as_view(), name='criar_empresa'),
    path('minha-empresa/', empresa.empresa_perfil, name='empresa_perfil'),
    path('deletar-empresa/', empresa.deletar_empresa, name='deletar_empresa'),
    path('editar-empresa/', empresa.editar_empresa, name='editar_empresa'),
    path('empresa/endereco', endereco.empresa_endereco, name='empresa_endereco'),
    path('empresa/endereco/adicionar', endereco.adicionar_endereco, name='empresa_endereco_adicionar'),
    path('empresa/endereco/editar', endereco.editar_endereco, name='editar_endereco'),
    path('empresa/endereco/deletar', endereco.deletar_endereco, name='deletar_endereco'),
    path('empresa/endereco/definir-endereco-padrao', endereco.definir_endereco_padrao, name='definir_endereco_padrao'),
]

apps/usuarios/urls.py
from django.urls import path

from .views import usuario
from .views import endereco

app_name = 'usuarios'

urlpatterns = [
    path('cadastro', usuario.SignUp.as_view(), name='cadastrousuario'),
    path('login', usuario.LoginCustomizado.as_view(), name='login'),
    path('resetar-senha', usuario.EmailTokenSenha.as_view(), name='resetarsenha'),
    path('resetar-senha-sucesso-email', usuario.MensagemResetarSenhaEmail.as_view(), name='sucessoresetarsenha'),
    path('reset/<uidb64>/<token>', usuario.ResetarSenha.as_view(), name='novasenha'),
    path('redifinicao-completa', usuario.ResetarSenhaMensagemCompleta.as_view(), name='redifinicaocompleta'),
    path('alterar-senha', usuario.AlteracaoSenha.as_view(), name='alterarsenha'),
    path('criar-perfil', usuario.CriarPerfilUsuario.as_view(), name='criarperfil'),
    path('perfil', usuario.perfil_principal, name='perfil_principal'),
    path('perfil/configuracao', usuario.perfil_configuracao, name='perfil_configuracao'),
    path('perfil/endereco', endereco.perfil_endereco, name='perfil_endereco'),
    path('perfil/endereco/adicionar', endereco.adicionar_endereco, name='perfil_endereco_adicionar'),
    path('perfil/endereco/editar', endereco.editar_endereco, name='editar_endereco'),
    path('perfil/endereco/deletar', endereco.deletar_endereco, name='deletar_endereco'),
    path('perfil/endereco/definir-endereco-padrao', endereco.definir_endereco_padrao, name='definir_endereco_padrao'),
    path('ajax/carregar-cidades/', endereco.carregar_cidades, name='ajax_carregar_cidades'),
    path('ajax/verificar-cep/', endereco.verificar_cep, name='verificar_cep'),
]

apps/vitrines/urls.py
from django.urls import path

from apps.vitrines.views import (
    CriarVitrine,
    listar_vitrine,
    deletar_vitrine,
    editar_vitrine
)

app_name = 'vitrines'

urlpatterns = [
    path('criar-vitrine/', CriarVitrine.as_view(), name='criar_vitrine'),
    path('minha-vitrine/', listar_vitrine, name='minha_vitrine'),
    path('editar-vitrine/', editar_vitrine, name='editar_vitrine'),
    path('deletar-vitrine/', deletar_vitrine, name='deletar_vitrine')
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', include('apps.ecommerce.urls')),
    path('usuarios/', include('apps.usuarios.urls')),
    path('empresas/', include('apps.empresas.urls')),
    path('vitrines/', include('apps.vitrines.urls')),
    path('produtos/', include('apps.produtos.urls')),
    path('pedidos/', include('apps.carrinhos.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/usuarios/views/endereco.py
import requests
import logging

from django.http import JsonResponse
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404, redirect

from ..forms import EnderecoForm
from ..models import Cidade, Estado, Endereco

logger = logging.getLogger(__name__)


@login_required(login_url='/usuarios/login')
def perfil_endereco(request):
    enderecos = Endereco.objects.filter(usuario=request.user, empresa=None, status=True)

    contexto = {
        'enderecos': enderecos,
        'usuario': request.user
    }

    return render(request, 'usuarios/endereco/perfil-endereco.html', contexto)


@login_required(login_url='/usuarios/login')
def adicionar_endereco(request):

    if request.method == "POST":

        endereco = verificar_endereco_adicionar(request.POST['estado'],
            request.POST['cidade'],
            request.POST['cep'],
            request.POST['bairro'],
            request.POST['rua'],
            request.POST['numero'],
            request.POST['complemento']
        )

        if endereco != '':
            endereco.usuario = request.user

            # verifica se é o primeiro endereco, se sim torna-lo padrao
            enderecos = Endereco.objects.filter(usuario=request.user,empresa=None, status=True)
            if len(enderecos) == 0:
                endereco.padrao = True

            endereco.save()
            return redirect('usuarios:perfil_endereco')
    else:
        form = EnderecoForm()

    estados = buscar_estados_api()
    contexto = {
        'form': form,
        'estados': estados,
        'usuario': request.user
    }

    return render(request, 'usuarios/endereco/perfil-endereco-adicionar.html', contexto)


@login_required(login_url='/usuarios/login')
def deletar_endereco(request):
    endereco = get_object_or_404(Endereco, pk=request.POST['endereco'])
    era_padrao = endereco.padrao
    endereco.padrao = False
    endereco.status = False
    endereco.save()

    if era_padrao:
        enderecos = Endereco.objects.filter(usuario=request.user, empresa=None, status=True)

        # se o endereço deletado era padrão e houver outro, trocar automaticamente
        if len(enderecos) > 0:
            endereco = get_object_or_404(Endereco, pk=enderecos[0].pk)
            endereco.padrao = True
            endereco.save()

    return redirect('usuarios:perfil_endereco')


@login_required(login_url='/usuarios/login')
def editar_endereco(request):
    endereco = get_object_or_404(Endereco, pk=request.POST['endereco'])

    if len(request.POST) > 2:

        endereco = verificar_endereco_editar(request.POST['endereco'],
            request.POST['estado'],
            request.POST['cidade'],
            request.POST['cep'],
            request.POST['bairro'],
            request.POST['rua'],
            request.POST['numero'],
            request.POST['complemento']
        )

        return redirect('usuarios:perfil_endereco')

    else:
        cidades = buscar_cidades_api(endereco.estado.sigla)
        nome_cidades = list(cidades.values())
        estados = buscar_estados_api()
        contexto = {
            'endereco': endereco,
            'estados': estados,
            'cidades': nome_cidades,
            'usuario': request.user
        }

        return render(request, 'usuarios/endereco/perfil-endereco-editar.html', contexto)


@login_required(login_url='/usuarios/login')
def definir_endereco_padrao(request):
    enderecos = Endereco.objects.filter(usuario=request.user, padrao=True)

    if len(enderecos) > 0:
        endereco = get_object_or_404(Endereco, pk=enderecos[0].pk)
        endereco.padrao = False
        endereco.save()

    endereco = get_object_or_404(Endereco, pk=request.POST['endereco'])
    endereco.padrao = True
    endereco.save()

    return redirect('usuarios:perfil_endereco')


# AJAX
def carregar_cidades(request):
    sigla = request.GET.get('estado').split('|')[-1]
    logger.debug('sigla: {}'.format(sigla))

    cidades = buscar_cidades_api(sigla)

    if request.is_ajax():
        return JsonResponse({'cidades': cidades})

# AJAX
def verificar_cep(request):
    cep = 'https://viacep.com.br/ws/{}/json/'.format(request.GET.get('cep'))
    requisicao_cep = requests.get(cep)

    try:
        lista = requisicao_cep.json()
    except ValueError:
        logger.critical("Não encontrou o cep")

    dicionario = {0: lista}

    if request.is_ajax():
        return JsonResponse({'cep': dicionario})

def verificar_endereco_adicionar(estado,cidade,cep,bairro,rua,numero,complemento):

    dicionario = verificar_estado_cidade_bd(estado, cidade)
    novo_estado = dicionario[0]
    nova_cidade = dicionario[1]

    sigla = estado.split('|')[-1]
    nome = estado.split('|')[0]

    novo_estado = Estado.objects.get(nome=nome, sigla=sigla)

    nova_cidade = Cidade.objects.get(
        nome=cidade,
        estado_id=novo_estado.pk
    )

    novo_endereco = dict(
        estado=novo_estado,
        cidade=nova_cidade,
        cep=cep,
        bairro=bairro,
        rua=rua,
        numero=numero,
        complemento=complemento
    )
    form = EnderecoForm(novo_endereco)

    if form.is_valid():
        endereco = form.save(commit=False)

        return endereco
    else:
        return ''

def verificar_endereco_editar(endereco,estado,cidade,cep,bairro,rua,numero,complemento):

    endereco = get_object_or_404(Endereco, pk=endereco)

    sigla = estado.split('|')[-1]

    if endereco.estado.sigla != sigla:
        nome = estado.split('|')[0]
        novo_estado = Estado.objects.get(nome=nome, sigla=sigla)
        endereco.estado = novo_estado

    if endereco.cidade.nome != cidade:
        nova_cidade = Cidade.objects.get(
            nome=cidade,
            estado_id=endereco.estado.pk
        )
        endereco.cidade = nova_cidade

    endereco.cep = cep
    endereco.bairro = bairro
    endereco.rua = rua
    endereco.numero = numero

    endereco.complemento = complemento

    endereco.save()

def verificar_estado_cidade_bd(estado, cidade):

    sigla = estado.split('|')[-1]
    nome = estado.split('|')[0]

    logger.debug(estado)
    logger.debug(nome)

    # consulta '.objects.get_or_create' retorna tupla
    buscar_estado = Estado.objects.get_or_create(nome = nome, sigla = sigla)
    # consulta '.objects.get' retorna objeto, como preciso da pk do respectivo objeto, faço nova consulta
    estado = Estado.objects.get(nome = nome, sigla = sigla)

    buscar_cidade = Cidade.objects.get_or_create(nome = cidade, estado_id = estado.pk)
    cidade = Cidade.objects.get(nome = cidade, estado_id = estado.pk)

    dicionario = {}
    dicionario[0] = estado
    dicionario[1] = cidade

    return dicionario


def buscar_estados_api():
    # busca na api do ibge os estados por ordem de nome
    # obs:Você pode copiar e colar o link no navegador para ver o arquivo Json gerado
    estados = 'https://servicodados.ibge.gov.br/api/v1/localidades/estados?orderBy=nome'

    # indica que quero obter os dados dessa requisição através do método .get()
    requisicao_estados = requests.get(estados)

    dicionario = {}

    try:
        # indica que quero desserializar, no caso,
        # transformar as informações str para um dicionário através do método .json()
        lista = requisicao_estados.json()

        for indice, estados in enumerate(lista):
            # adiciona as tuplas com os estados
            dicionario[indice] = estados

    except ValueError:
        logger.critical("Não encontrou os estados")

    return dicionario


def buscar_cidades_api(sigla):
    cidades = 'https://servicodados.ibge.gov.br/api/v1/localidades/estados/{}/municipios'.format(sigla)
    requisicao_cidades = requests.get(cidades)

    dicionario = {}

    try:
        lista = requisicao_cidades.json()

        for indice, cidades in enumerate(lista):
            # apenas filtrando os dados do objeto em cidades para pegar apenas o nome,
            # dessa forma facilita a manipulação dos dados com js
            dicionario[indice] = cidades.get('nome')
    except ValueError:
        logger.critical("Não encontrou as cidades")

    return dicionario

templates/usuarios/dados_perfil_usuario.html
{% extends 'usuarios/perfil-principal.html' %}
{% load static %}

{% block content %}

	<main class="col-md-9">

		<article class="card mb-3">
			<div class="card-body">
				{% if not usuario.status %}
				<div>
				<h5 class="text-center mt-4">
					  <strong>
					 Você precisa realizar o cadastro de seu perfil
					  </strong>
				 <img src="{% static 'ecommerce/images/atencao.png' %}"/>
				 </h5>
					<div class="d-flex justify-content-center">

				<a href="{% url 'usuarios:criarperfil' %}" class="btn btn-secondary">Cadastrar perfil</a>
					</div>
				</div>
				{% elif usuario.status %}
				<figure class="icontext">
						<div class="icon">
							{% if not user.foto %}
								<img class="rounded-circle img-sm" src="{% static 'ecommerce/images/avatars/user-icon.png' %}">
								<input type="hidden" name="user icons png from pngtree.com" href='https://pngtree.com/so/user-icons'>
								</input>
							{% else %}
								<img class="rounded-circle img-sm" src="{{ usuario.foto.url }}">
							{% endif %}
						</div>
						<div class="text">
							<strong> {{ user.first_name }} {{user.last_name }} </strong> <br>
							<p class="mb-2"> {{ user.email }}  </p>
							<button class="btn btn-light btn-sm" data-toggle="modal" data-target="#modal-foto">Alterar foto</button>

							{% include 'usuarios/modal-foto.html' %}

						</div>
				</figure>
				<hr>
				<div class="container">
					<div class="row">
						<div class="col-lg-7">
							<p>
								<i class="fa fa-map-marker text-muted"></i> &nbsp; Meus endereços:
								<br>
								<div class="form-inline">
									{% for endereco in enderecos %}
									{{ endereco.cidade.nome }}, {{ endereco.rua }},
									{{ endereco.bairro }}, {{ endereco.numero}} &nbsp
									<form action="{% url 'usuarios:editar_endereco' %}" method="post">
										{% csrf_token %}
										<button type="submit" class="btn btn-light btn-sm" name="endereco"
										value="{{ endereco.pk }}" style="background-color:white; border-color:white;">
										Editar
									</button>
								</form>
								<br>
								{% empty %}
								<p> Você ainda não possui nenhum endereço </p>
								{% endfor %}
							</div>
						</p>
						<br>
						</div>
					<div class="col-lg-5">
						<p>
							<i class="fas fa-phone text-muted"></i> &nbsp; Meus telefones:
							 <br>
							 <div class="form-inline">
								{% for telefone in telefones %}
									{{ telefone.tipo }}: {{ telefone.numero }} &nbsp
									<form method="post">
										{% csrf_token %}
										<a href="{% url 'usuarios:perfil_configuracao' %}" class="btn btn-light btn-sm"
											style="background-color:white; border-color:white;">
											Editar
										</a>
									</form>
									<br>
									{% empty %}
										<p> Você ainda não possui nenhum telefone </p>
								{% endfor %}
							</div>
						</p>
					</div>
					</div>
				</div>

			</div>
				<article class="card-group card-stat">
					<figure class="card bg">
						<div class="p-3">
							 <h4 class="title">38</h4>
							<span>Pedidos</span>
						</div>
					</figure>
					<figure class="card bg">
						<div class="p-3">
							 <h4 class="title">5</h4>
							<span>Lista de desejos</span>
						</div>
					</figure>
					<figure class="card bg">
						<div class="p-3">
							 <h4 class="title">12</h4>
							<span>Aguardando entrega</span>
						</div>
					</figure>
					<figure class="card bg">
						<div class="p-3">
							 <h4 class="title">50</h4>
							<span>Produtos e serviços entregues</span>
						</div>
					</figure>
				</article>
				<br><br><br>
				{% include 'usuarios/menu-pedidos-perfil.html' %}
			</div> <!-- card-body .// -->
		</article> <!-- card.// -->
	{% endif %}
	</main>
	<!-- card.// -->


	<script src="{% static 'js/validarFoto.js' %}" type="text/javascript"></script>

{% endblock %}

templates/usuarios/formulario-endereco-jQuery.html
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery.mask/1.14.0/jquery.mask.js"></script>

<script>

	// formatando o input do cep
	$(document).ready(function () {
			var $campo = $("#cep");
			$campo.mask('00000-000', {reverse: true});
	});

	// Seleciona o select dos estados pelo id do select
	$("#estado").change(function() {

		// pego o valor do option selecionado
		var estado = $('#estado').find(":selected").val();

		// limpa as options do select cidades pelo id do select
		$("#cidade").empty();
		$('#cidade').append(`<option value="" disabled selected hidden>Carregando cidades..</option>`);

		// printa no console do navegador o estado selecionado
		// console.log(estado);

		// executo o ajax e passo a url e informação desejada
		$.ajax({
			 url: '{% url "usuarios:ajax_carregar_cidades" %}',
			 data: {
			   'estado': estado
			 },

			 // caso o ajax ocorrer corretamente
			 success: function (data) {

				// printa no console os dados retornados
			 	// console.log("buscou as cidades:");
				// console.log(data);

				// printa a quantidade de chaves do objeto 'cidades'
				// console.log(Object.keys(data['cidades']).length);

				$("#cidade").empty();

				$('#cidade').append('<option value="" disabled selected hidden>Selecione sua cidade</option>');

					for(var i=0; i < 	Object.keys(data['cidades']).length; i++ ){

						// pega o objeto que está na chave [i]
						var cidade = data['cidades'][i];
						// console.log(cidade);

						$('#cidade').append(`<option id="cidade" name="cidade" value='${cidade}'>${cidade} </option>`);

					}
			  }
			});
	});
</script>

<script>
	$("#cidade").change(function() {
		var estado = $('#estado').find(":selected").val();
		var cidade = $('#cidade').find(":selected").val();

		console.log("estado antes:");
		console.log(estado);

		$.ajax({
			 url: '{% url "usuarios:verificar_cidade_bd" %}',
			 data: {
				 'estado': estado,
				 'cidade': cidade
			 },
				 success: function (data) {

					 // printa os dados retornados pelo ajax caso queira ver no console
					 // console.log(data);
					 // console.log("estado depois:");
					 // console.log(data['dicionario'][0]);
					 // console.log("cidade:");
					 // console.log(data['dicionario'][1]);

				 }
		});
	});
</script>

<script>
	$(document).ready(function(){
		$("#cep").keyup(function(){

			var cep = this.value;

			if(cep.length == 9){

					$.ajax({
						 url: '{% url "usuarios:verificar_cep" %}',
						 data: {
							 'cep': cep
						 },
							 success: function (data) {

								 // printa os dados retornados pelo ajax caso queira ver no console
								 // console.log(data);

								 try{
									 // retorna uma array dos pares de propriedade [chave, valor] com chave de string do próprio objeto
									 var endereco = Object.entries(data['cep'][0])

									 document.getElementById("cep").style.borderColor = 'lightGray';
									 $("#cep_msg").text('');

									 var rua = endereco[1];
									 document.getElementById("rua").value = rua[1];

									 var bairro = endereco[3];
									 document.getElementById("bairro").value = bairro[1];

								 }catch{
									 document.getElementById("cep").style.borderColor = 'red';

									 $("#cep_msg").text('Cep inválido');
								 }
							 }
					});
			}

		});
	});
</script>

<script>
	// validar os campos do formulário
	(function() {
		'use strict';
		window.addEventListener('load', function() {
			// Fetch all the forms we want to apply custom Bootstrap validation styles to
			var forms = document.getElementsByClassName('needs-validation');
			// Loop over them and prevent submission
			var validation = Array.prototype.filter.call(forms, function(form) {
				form.addEventListener('submit', function(event) {
					if (form.checkValidity() === false) {
						event.preventDefault();
						event.stopPropagation();
					}
					form.classList.add('was-validated');
				}, false);
			});
		}, false);
	})();
</script>

templates/usuarios/menu-perfil.html
<aside class="col-md-3 mb-3">
  <nav class="list-group">
    <a class="list-group-item" href="{% url 'usuarios:perfil_principal' %}"> Visão geral da conta </a>
    <a class="list-group-item" href="{% url 'empresas:empresa_perfil' %}"> Minha empresa</a>
    <a class="list-group-item" href="{% url 'vitrines:minha_vitrine' %}"> Minha vitrine </a>
    <a class="list-group-item" href="{% url 'usuarios:perfil_endereco' %}"> Meus endereços </a>
    <a class="list-group-item" href="{% url 'pedidos:listar_pedidos' %}"> Meus pedidos </a>
    <a class="list-group-item" href="page-profile-wishlist.html"> Minha lista de desejos </a>
    <a class="list-group-item" href="page-profile-seller.html"> Meus itens de venda </a>
    <a class="list-group-item" href="{% url 'usuarios:perfil_configuracao' %}"> Configurações </a>
    <a class="list-group-item" href="{% url 'logout' %}"> Sair </a>
  </nav>
</aside> <!-- col.// -->

templates/usuarios/perfil-endereco.html
{% extends 'ecommerce/base.html' %}
{% load static %}

{% block body %}

<body>

<!-- ========================= SECTION PAGETOP ========================= -->
<section class="section-pagetop bg-gray">
<div class="container">
	<h2 class="title-page">Minha conta</h2>
</div> <!-- container //  -->
</section>
<!-- ========================= SECTION PAGETOP END// ========================= -->


<!-- ========================= SECTION CONTENT ========================= -->
<section class="section-content padding-y">
	<div class="container">

	<div class="row">
		{% block menu-perfil %}
		   {% include "usuarios/menu-perfil.html" %}
		{% endblock %}
	<main class="col-md-9">
		<a href="{% url 'usuarios:perfil_endereco_adicionar' %}" class="btn btn-light mb-3 mt-2"> <i class="fa fa-plus"></i>
			 Adicionar novo endereço
		</a>
        <div class="row">
					{% for endereco in enderecos %}
	            <div class="col-md-6">
	                <article class="box mb-4">
	                    <h6>{{ endereco.cidade.nome }}, {{ endereco.estado.nome }}</h6>
	                    <p>{{ endereco.bairro }} <br> {{ endereco.rua }}, {{ endereco.numero }}  </p>
												<div class="form-inline">
												{% if endereco.padrao %}
													<a href="#" class="btn btn-light enable" style="border-color: green;">
														<i class="fa fa-check" style="color: green;"></i>
														Padrão
													</a>
												{% else %}
													<form action="{% url 'usuarios:definir_endereco_padrao' %}" method="post">
														{% csrf_token %}
														<button type="submit" class="btn btn-light enable" name="endereco" value="{{ endereco.pk }}">
															<i class="fa fa-check"></i>
															Padrão
														</button>
													</form>
												{% endif %}
													&nbsp;
													<form action="{% url 'usuarios:editar_endereco' %}"  method="post">
														{% csrf_token %}
														<button type="submit" class="btn btn-light" name="endereco" value="{{ endereco.pk }}">
															<i class="fa fa-pen"></i>
														</button>
													</form>
														&nbsp;
														<form action="{% url 'usuarios:deletar_endereco' %}"  method="post">
															{% csrf_token %}
															<button type="submit" class="btn btn-light" name="endereco" value="{{ endereco.pk }}">
																<i class="text-danger fa fa-trash"></i>
															</button>
														</form>
													</div>
	                </article>
	            </div>  <!-- col.// -->
          {% empty %}
							<p> &nbsp; Você ainda não possui nenhum endereço </p>
					{% endfor %}
        </div> <!-- row.// -->

	</main> <!-- col.// -->
</div>

</div> <!-- container .//  -->
</section>
<!-- ========================= SECTION CONTENT END// ========================= -->

</body>

<br><br><br><br><br><br>

{% endblock %}

templates/usuarios/perfil-principal.html
{% extends 'ecommerce/base.html' %}
{% load static %}

{% block body %}

<body>

<!-- ========================= SECTION PAGETOP ========================= -->
<section class="section-pagetop bg-gray">
<div class="container">
	<h2 class="title-page">Minha conta</h2>
</div> <!-- container //  -->
</section>
<!-- ========================= SECTION PAGETOP END// ========================= -->

<!-- ========================= SECTION CONTENT ========================= -->
<section class="section-content padding-y">
<div class="container">

<div class="row">
 <!-- col.// -->
 			{% if perfil_usuario %}
	      {% block menu %}
	        {% include 'usuarios/menu-perfil.html' %}
				{% endblock %}
			{% else %}
				{% block menu-empresa %}
					{% include 'empresas/menu-perfil-empresa.html' %}
				{% endblock %}
			{% endif %}

		   {% block content %}

				<figure class="icontext">
						<div class="icon">
							{% if not user.foto %}
								<img class="rounded-circle img-sm" src="{% static 'ecommerce/images/avatars/user-icon.png' %}">
								<input type="hidden" name="user icons png from pngtree.com" href='https://pngtree.com/so/user-icons'>
								</input>
							{% else %}
								<img class="rounded-circle img-sm border" src="{{ user.foto.url }}">
							{% endif %}
						</div>
						<div class="text">
							<strong> {{ user.first_name }} {{user.last_name }} </strong> <br>
							<p class="mb-2"> {{ user.email }}  </p>

							<a href="{% url 'usuarios:perfil_configuracao' %}" class="btn btn-light btn-sm">Editar</a>

							<a href="#" class="btn btn-light btn-sm">Editar</a>
							<a href="{% url 'usuarios:alterarsenha' %}" class="btn btn-secondary btn-block">Alterar senha</a>

						</div>
				</figure>
				<hr>
				<p>
					<i class="fa fa-map-marker text-muted"></i> &nbsp; Meus endereços:
					 <br>
					 	{% for endereco in enderecos %}
						<div class="form-inline">
							{{ endereco.cidade.nome }}, {{ endereco.rua }},
							{{ endereco.bairro }}, {{ endereco.numero}} &nbsp
							<form action="{% url 'usuarios:editar_endereco' %}"  method="post">
								{% csrf_token %}
								<button type="submit" class="btn btn-light btn-sm" name="endereco"
									value="{{ endereco.pk }}" style="background-color:white; border-color:white;">
									Editar
								</button>
							</form>
							<br>
							{% empty %}
								<p> Você ainda não possui nenhum endereço </p>
						</div>
						{% endfor %}
				</p>
				<article class="card-group card-stat">
					<figure class="card bg">
						<div class="p-3">
							 <h4 class="title">38</h4>
							<span>pedidos</span>
						</div>
					</figure>
					<figure class="card bg">
						<div class="p-3">
							 <h4 class="title">5</h4>
							<span>Lista de desejos</span>
						</div>
					</figure>
					<figure class="card bg">
						<div class="p-3">
							 <h4 class="title">12</h4>
							<span>Aguardando entrega</span>
						</div>
					</figure>
					<figure class="card bg">
						<div class="p-3">
							 <h4 class="title">50</h4>
							<span>Produtos e serviços entregues</span>
						</div>
					</figure>
				</article>
	     {% endblock %}


	 <!-- col.// -->
</div>

</div> <!-- container .//  -->
</section>
<!-- ========================= SECTION CONTENT END// ========================= -->

</body>

{% endblock %}