apps/produtos/urls.py
from django.urls import path

from apps.produtos.views import *

app_name = 'produtos'

urlpatterns = [
     path('criar-produto/', CriarProduto.as_view(), name='criar_produto'),
     path('ajax/carregar-subcategoria/', carregar_subcategorias, name='ajax_carregar_subcategorias'),
     path('deletar-produto/', deletar_produto, name='deletar_produto'),
     path('editar-produto/', editar_produto, name='editar_produto'),
     path('visualizar-produto/<str:nome>/<int:pk>/', visualizar_produto, name='visualizar_produto'),
]

apps/usuarios/urls.py
from django.urls import path

from .views import usuario
from .views import endereco

app_name = 'usuarios'

urlpatterns = [
    path('cadastro', usuario.SignUp.as_view(), name='cadastrousuario'),
    path('login', usuario.LoginCustomizado.as_view(), name='login'),
    path('resetar-senha', usuario.EmailTokenSenha.as_view(), name='resetarsenha'),
    path('resetar-senha-sucesso-email', usuario.MensagemResetarSenhaEmail.as_view(), name='sucessoresetarsenha'),
    path('reset/<uidb64>/<token>', usuario.ResetarSenha.as_view(), name='novasenha'),
    path('redifinicao-completa', usuario.ResetarSenhaMensagemCompleta.as_view(), name='redifinicaocompleta'),
    path('alterar-senha', usuario.AlteracaoSenha.as_view(), name='alterarsenha'),
    path('criar-perfil', usuario.CriarPerfilUsuario.as_view(), name='criarperfil'),
    path('perfil', usuario.perfil_principal, name='perfil_principal'),
    path('perfil/configuracao', usuario.perfil_configuracao, name='perfil_configuracao'),
    path('perfil/endereco', endereco.perfil_endereco, name='perfil_endereco'),
    path('perfil/endereco/adicionar', endereco.adicionar_endereco, name='perfil_endereco_adicionar'),
    path('perfil/endereco/editar', endereco.editar_endereco, name='editar_endereco'),
    path('perfil/endereco/deletar', endereco.deletar_endereco, name='deletar_endereco'),
    path('perfil/endereco/definir-endereco-padrao', endereco.definir_endereco_padrao, name='definir_endereco_padrao'),
    path('ajax/carregar-cidades/', endereco.carregar_cidades, name='ajax_carregar_cidades'),
    path('ajax/verificar-cep/', endereco.verificar_cep, name='verificar_cep'),
]

apps/vitrines/urls.py
from django.urls import path

from apps.vitrines.views import (
    CriarVitrine,
    listar_vitrine,
    deletar_vitrine,
    editar_vitrine
)

app_name = 'vitrines'

urlpatterns = [
    path('criar-vitrine/', CriarVitrine.as_view(), name='criar_vitrine'),
    path('minha-vitrine/', listar_vitrine, name='minha_vitrine'),
    path('editar-vitrine/', editar_vitrine, name='editar_vitrine'),
    path('deletar-vitrine/', deletar_vitrine, name='deletar_vitrine')
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', include('apps.ecommerce.urls')),
    path('usuarios/', include('apps.usuarios.urls')),
    path('empresas/', include('apps.empresas.urls')),
    path('vitrines/', include('apps.vitrines.urls')),
    path('produtos/', include('apps.produtos.urls')),
    path('pedidos/', include('apps.carrinhos.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/vitrines/models.py
from django.db import models

from mysite import settings

from apps.empresas.models import Empresa

class Vitrine(models.Model):
    nome = models.CharField('Nome', max_length=60, help_text='Obrigatório')
    descricao = models.CharField('Descrição', max_length=450, help_text='Obrigatório')
    empresa = models.ForeignKey(Empresa, on_delete=models.PROTECT,null=True, default="")
    vendedor = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, default="")
    status = models.BooleanField('Ativo?', default=True)

    class Meta:
        verbose_name = 'Vitrine'
        verbose_name_plural = 'Vitrines'

    def __str__(self):
        return '{}-{}'.format(self.nome, self.descricao)

apps/vitrines/forms.py
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Row, Column
from django import forms
from django.forms import Textarea

from apps.vitrines.models import Vitrine


class CadastroVitrine(forms.ModelForm):
    class Meta:
        model = Vitrine
        fields = ('nome', 'descricao')
        widgets = {
            'descricao': Textarea(attrs={'cols': 40, 'rows': 10})
        }

    def __init__(self, *args, **kwargs):
        super(CadastroVitrine, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.layout = Layout(
            Row(
                Column('nome', css_class='form-group col-md-6'),
                Column('descricao', css_class='form-group col-md-6'),
            )
        )
        self.fields['nome'].widget.attrs['placeholder'] = 'Insira o nome da vitrine'
        self.fields['descricao'].widget.attrs['placeholder'] = 'Insira a descrição da vitrine'

apps/vitrines/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, get_object_or_404, redirect

from django.views.generic import (
    CreateView,
)

from apps.produtos.models import Produto, ImagemProduto
from apps.usuarios.models import CustomUsuario
from apps.vitrines.forms import CadastroVitrine
from apps.vitrines.models import Vitrine

recuperar_id_editar_vitrine = {}
recuperar_id_deletar_vitrine = {}


def consulta_vitrine(usuario):
    query_set = Vitrine.objects.filter(vendedor=usuario, status=True)
    return query_set


@login_required(login_url='/usuarios/login')
def deletar_vitrine(request):
    if len(request.POST) == 2:
        vitrine = get_object_or_404(Vitrine, pk=request.POST.get('id'))
        recuperar_id_deletar_vitrine['vitrine'] = vitrine
        vitrine.status = False
        vitrine.save()

    if not recuperar_id_deletar_vitrine['vitrine'].status:
        messages.success(request, 'Vitrine deletada com sucesso!')

    return redirect('vitrines:minha_vitrine')


@login_required(login_url='/usuarios/login')
def listar_vitrine(request):
    usuario_logado = CustomUsuario.objects.get(email=request.user)

    query_set = consulta_vitrine(usuario_logado)

    if query_set is None:
        tamanho_resultado_query_set = 0
    else:
        tamanho_resultado_query_set = len(query_set)

    vitrine = Vitrine.objects.filter(vendedor=usuario_logado, status=True).first()
    produtos = Produto.objects.filter(vitrine=vitrine, status=True)
    imagens_produtos = ImagemProduto.objects.filter(produto__in=produtos)

    #No resultado query_set verifico se já existe uma vitrine ou não, caso ele já existe,
    #redireciono e mostro os dados da vitrine, caso contrário o usuário deverá cadastrar a sua vitrine
    contexto = {
        'usuario': usuario_logado,
        'vitrine': vitrine,
        'resultado_busca_vitrine': tamanho_resultado_query_set,
        'produtos': produtos,
        'imagens_produtos': imagens_produtos
    }

    return render(request, 'vitrines/vitrine_listar.html', contexto)


class CriarVitrine(LoginRequiredMixin, CreateView):
    login_url = '/usuarios/login'

    def get(self, request, *args, **kwargs):
        usuario_logado = CustomUsuario.objects.get(email=request.user)
        form = super().get_form(CadastroVitrine)

        query_set = consulta_vitrine(usuario_logado)
        if query_set is None:
            tamanho_resultado_query_set = 0
        else:
            tamanho_resultado_query_set = len(query_set)

        contexto = {
            'usuario': usuario_logado,
            'form': form,
            'resultado_busca_vitrine': tamanho_resultado_query_set
        }

        return render(request, 'vitrines/cadastros/vitrine_cadastro.html', contexto)

    def post(self, request, *args, **kwargs):
        form = self.get_form(CadastroVitrine)

        if form.is_valid():
            usuario_logado = CustomUsuario.objects.get(email=request.user)
            nome = form.cleaned_data['nome']
            descricao = form.cleaned_data['descricao']
            vitrine = Vitrine.objects.create(nome=nome, descricao=descricao, vendedor=usuario_logado)

            try:
                if request.POST['empresa']:
                    vitrine.empresa = request.user.empresa
            except:
                vitrine.empresa = None

            vitrine.save()

            messages.success(request, 'Vitrine cadastrada com sucesso!')
            return redirect('vitrines:minha_vitrine')
        else:
            messages.error(request, 'Erro ao enviar formulário!')

        usuario_logado = CustomUsuario.objects.get(email=request.user)

        contexto = {
            'form': form,
            'usuario': usuario_logado
        }

        return render(request, 'vitrines/cadastros/vitrine_cadastro.html', contexto)

@login_required(login_url='/usuarios/login')
def editar_vitrine(request):
    if len(request.POST) == 2:
        if not recuperar_id_editar_vitrine:
            recuperar_id_editar_vitrine['id'] = request.POST.get('id')

    vitrine = retornar_vitrine()
    if str(request.method) == 'POST':
        if len(request.POST) > 2:
            form = CadastroVitrine(request.POST, instance=vitrine)

            if form.is_valid():
                nome = form.cleaned_data['nome']
                descricao = form.cleaned_data['descricao']

                vitrine.nome = nome
                vitrine.descricao = descricao

                try:
                    if request.POST['empresa']:
                        vitrine.empresa = request.user.empresa
                except:
                    vitrine.empresa = None

                vitrine.save()
                messages.success(request, 'Vitrine editada com sucesso!')
                return redirect('vitrines:minha_vitrine')
            else:
                messages.error(request, 'Erro ao enviar formulário!')

    form = CadastroVitrine(instance=vitrine)
    usuario_logado = CustomUsuario.objects.get(email=request.user)

    contexto = {
        'form': form,
        'usuario': usuario_logado,
        'vitrine': vitrine
    }

    return render(request, 'vitrines/cadastros/vitrine_editar.html', contexto)


def retornar_vitrine():
    if recuperar_id_editar_vitrine:
        vitrine = get_object_or_404(Vitrine, pk=recuperar_id_editar_vitrine['id'])
        return vitrine

templates/vitrines/page-profile-seller.html
{% extends 'usuarios/perfil-principal.html' %}
{% load static %}

{% block content %}
<body>
	<main class="col-md-9">



		{% if not usuario.status %}
          <div>
              <h5 class="text-center mt-4">
                  <strong>
					 Você precisa realizar o cadastro de seu perfil para adicionar a sua empresa
                  </strong>
                  <img src="{% static 'ecommerce/images/atencao.png' %}"/>
                  </h5>
					<div class="d-flex justify-content-center">

				<a href="{% url 'usuarios:criarperfil' %}" class="btn btn-secondary">Cadastrar perfil</a>
					</div>
				</div>

		{% elif usuario.status %}


		<article class="card">
			<div class="card-body">
						{% if resultado_busca_vitrine == 0 %}
 			<div>
              <h5 class="text-center mt-4">
                  <strong>
					 Você precisa realizar o cadastro de sua vitrine
                  </strong>
                  <img src="{% static 'ecommerce/images/atencao.png' %}"/>
                  </h5>
					<div class="d-flex justify-content-center">

				<a href="{% url 'vitrines:criar_vitrine' %}" class="btn btn-primary">Cadastrar vitrine</a>
					</div>
				</div>

	<hr>
						{% else %}
						<div class="text">
							<strong>Nome da vitrine:</strong> {{ vitrine.nome }} <br>
							<strong>Descrição:</strong> {{ vitrine.descricao }}

						</div>
				<br>
				<a href="#" onclick="editarVitrine({{ vitrine.id }})" class="btn btn-secondary mb-3">Editar <i class="fa fa-pen"></i> </a>
				<a href="#" class="btn btn-secondary mb-3" onclick="deletarVitrine({{ vitrine.id }})"> Deletar <i class="text-danger fa fa-trash"></i>  </a>

						<hr>


		<div class="row">
				<div class="col-md-4">
					<figure class="card card-product-grid">
						<div class="img-wrap">
							<img src="images/items/1.jpg">
						</div> <!-- img-wrap.// -->
						<figcaption class="info-wrap">
								<a href="#" class="title mb-2">Hot sale unisex New Design Shirt for sport polo shirts latest design</a>
								<div class="price-wrap mb-3">
									<span class="price">$32.00-$40.00</span>
									<small class="text-muted">/per item</small>
								</div> <!-- price-wrap.// -->
								<a href="#" class="btn btn-outline-primary"> <i class="fa fa-pen"></i> Edit </a>
								<a href="#" class="btn btn-primary"> <i class="fa fa-eye"></i> View  </a>

								<hr>
								<a href="#" class="btn btn-success btn-block">  Promote </a>
						</figcaption>
					</figure>
				</div> <!-- col.// -->

				<div class="col-md-4">
					<figure class="card card-product-grid">
						<div class="img-wrap">
							<img src="images/items/2.jpg">
						</div> <!-- img-wrap.// -->
						<figcaption class="info-wrap">
								<a href="#" class="title mb-2">High Quality Winter PU Rain Jacket with Padding for Men's outdoor</a>
								<div class="price-wrap mb-3">
									<span class="price">$41.00-$50.00</span>
									<small class="text-muted">/per item</small>
								</div> <!-- price-wrap.// -->
								<a href="#" class="btn btn-outline-primary"> <i class="fa fa-pen"></i> Edit </a>
								<a href="#" class="btn btn-primary"> <i class="fa fa-eye"></i> View  </a>

								<hr>
								<a href="#" class="btn btn-success btn-block">  Promote </a>
						</figcaption>
					</figure>
				</div> <!-- col.// -->

				<div class="col-md-4">
					<figure class="card card-product-grid">
						<div class="img-wrap">
							<img src="images/items/1.jpg">
						</div> <!-- img-wrap.// -->
						<figcaption class="info-wrap">
								<a href="#" class="title mb-2">Cheap and Best demo clothe with latest Fashion styles for Men</a>
								<div class="price-wrap mb-3">
									<span class="price">$32.00-$40.00</span>
									<small class="text-muted">/per item</small>
								</div> <!-- price-wrap.// -->
								<a href="#" class="btn btn-outline-primary"> <i class="fa fa-pen"></i> Edit </a>
								<a href="#" class="btn btn-primary"> <i class="fa fa-eye"></i> View  </a>

								<hr>
								<a href="#" class="btn btn-success btn-block">  Promote </a>
						</figcaption>
					</figure>
				</div> <!-- col.// -->

				<div class="col-md-4">
					<figure class="card card-product-grid">
						<div class="img-wrap">
							<img src="images/items/4.jpg">
						</div> <!-- img-wrap.// -->
						<figcaption class="info-wrap">
								<a href="#" class="title mb-2">Cheap and Best demo clothe with latest Fashion styles for Men</a>
								<div class="price-wrap mb-3">
									<span class="price">$32.00-$40.00</span>
									<small class="text-muted">/per item</small>
								</div> <!-- price-wrap.// -->
								<a href="#" class="btn btn-outline-primary"> <i class="fa fa-pen"></i> Edit </a>
								<a href="#" class="btn btn-primary"> <i class="fa fa-eye"></i> View  </a>

								<hr>
								<a href="#" class="btn btn-success btn-block">  Promote </a>
						</figcaption>
					</figure>
				</div> <!-- col.// -->

				<div class="col-md-4">
					<figure class="card card-product-grid">
						<div class="img-wrap">
							<img src="images/items/5.jpg">
						</div> <!-- img-wrap.// -->
						<figcaption class="info-wrap">
								<a href="#" class="title mb-2">Cheap and Best demo clothe with latest Fashion styles for Men</a>
								<div class="price-wrap mb-3">
									<span class="price">$32.00-$40.00</span>
									<small class="text-muted">/per item</small>
								</div> <!-- price-wrap.// -->
								<a href="#" class="btn btn-outline-primary"> <i class="fa fa-pen"></i> Edit </a>
								<a href="#" class="btn btn-primary"> <i class="fa fa-eye"></i> View  </a>

								<hr>
								<a href="#" class="btn btn-success btn-block">  Promote </a>
						</figcaption>
					</figure>
				</div> <!-- col.// -->

			</div> <!-- row .//  -->

			</div>
			{% endif %}
			<!-- card-body.// -->
			{% endif %}
		</article>


	</main> <!-- col.// -->
<script src="https://cdn.jsdelivr.net/npm/sweetalert2@10"></script>
</body>
<script src="{% static 'js/editarVitrine.js' %}" type="text/javascript"></script>
<script src="{% static 'js/deletarVitrine.js' %}" type="text/javascript"></script>


<!-- ========================= SECTION CONTENT END// ========================= -->

{% if messages %}
    {% for m in messages %}
        {% if m.level == DEFAULT_MESSAGE_LEVELS.SUCCESS %}
        {{ message }}
        <script>
            Swal.fire({
              position: 'center',
              icon: 'success',
              title: 'Sucesso',
              text:'{{ m }}',
              showConfirmButton: true,
              confirmButtonColor: '#000080',
            })
        </script>
    {% endif %}
    {% endfor %}
{% endif %}
{% endblock %}

templates/vitrines/vitrine_listar.html
{% extends 'usuarios/perfil-principal.html' %}
{% load static %}

{% block content %}
<body>
	<main class="col-md-9">



		{% if not usuario.status %}
          <div>
              <h5 class="text-center mt-4">
                  <strong>
					 Você precisa realizar o cadastro de seu perfil para adicionar a sua empresa
                  </strong>
                  <img src="{% static 'ecommerce/images/atencao.png' %}"/>
                  </h5>
					<div class="d-flex justify-content-center">

				<a href="{% url 'usuarios:criarperfil' %}" class="btn btn-secondary">Cadastrar perfil</a>
					</div>
				</div>

		{% elif usuario.status %}


		<article class="card">
			<div class="card-body">
						{% if resultado_busca_vitrine == 0 %}
 			<div>
              <h5 class="text-center mt-4">
                  <strong>
					 Você precisa realizar o cadastro de sua vitrine
                  </strong>
                  <img src="{% static 'ecommerce/images/atencao.png' %}"/>
                  </h5>
					<div class="d-flex justify-content-center">

				<a href="{% url 'vitrines:criar_vitrine' %}" class="btn btn-primary">Cadastrar vitrine</a>
					</div>
				</div>

	<hr>
						{% else %}
				<h4 class="card-title mb-5">
					Minha vitrine
				</h4>
						<div class="text">
							<strong>Nome da vitrine:</strong> {{ vitrine.nome }} <br>
							<strong>Descrição:</strong> {{ vitrine.descricao }}

						</div>
				<br>
				<div class="row">
				<form method="POST" autocomplete="off">
					{% csrf_token %}
					<input  type="hidden"  name="campoID" value="{{ vitrine.id }}">

					<a href="#" onclick="editarVitrine()" class="btn btn-secondary mb-3">Editar vitrine <i class="fa fa-pen"></i> </a>
						<a href="#" class="btn btn-secondary mb-3" onclick="deletarVitrine()"> Deletar vitrine <i class="text-danger fa fa-trash"></i>  </a>
				</form>
					<div class="col-sm" style="padding-left:490px">
				<a href="{% url 'produtos:criar_produto' %}" class="btn btn-secondary mb-3" > Adicionar produto <i class="fa fa-plus"></i>  </a>
              	</div>
               </div>
						<hr>
			    <h4 class="card-title mb-5">
					Meus produtos
				</h4>
		<div class="row">

			{% if produtos.count == 0 %}
				<h5> Sua vitrine não possui nenhum produto </h5>
			{% endif %}
			{% for produto in produtos %}
				<div class="col-md-4">
					<figure class="card card-product-grid">
							<div class="img-wrap">
								{% for imagem in imagens_produtos %}
									{% if imagem.produto == produto %}
									<a href="{% url 'produtos:visualizar_produto' nome=produto.nome pk=produto.pk %}">
										<img class="zoom" src="{{ imagem.imagem.url }}">
									</a>
									{% endif %}
								{% endfor %}
							</div>
							<figcaption class="info-wrap">
								<a href="#" class="title mb-2">Nome do produto: {{ produto.nome }}</a>
								<div class="price-wrap mb-3">
									<span class="price">Preço: {{ produto.preco }}</span>
									<small class="text-muted">/por item</small>
								</div>
								<div class="price-wrap mb-3">
									<span>Quantidade: {{ produto.quantidade }}</span>
								</div>
								<div class="form-inline">
									<form method="POST" action="{% url 'produtos:editar_produto' %}" autocomplete="off">
										{% csrf_token %}
										<input  type="hidden" name="campoIDProduto" value="{{ produto.id }}">
										<button class="btn btn-outline-primary mb-3" type="submit" > Editar <i class="fa fa-pen"></i></button>
									</form>
									&nbsp;
									<form method="POST" autocomplete="off">
										{% csrf_token %}
										<input  type="hidden" name="campoIDProduto" value="{{ produto.id }}">
										<a href="#" class="btn btn-outline-danger mb-3" onclick="deletarProduto({{ produto.id }})"> Deletar <i class="fa fa-trash"></i>  </a>
									</form>
								</div>

								<hr>
									<a href="{% url 'produtos:visualizar_produto' nome=produto.nome pk=produto.pk %}"
										class="btn btn-success btn-block">
										Detalhes <i class="fa fa-info-circle"></i>
									</a>
							</figcaption>
					</figure>
				</div>
			{% endfor %}

			</div> <!-- row .//  -->

			</div>
			{% endif %}
			<!-- card-body.// -->
			{% endif %}
		</article>


	</main> <!-- col.// -->
<script src="https://cdn.jsdelivr.net/npm/sweetalert2@10"></script>
</body>
<script src="{% static 'js/editarVitrine.js' %}" type="text/javascript"></script>
<script src="{% static 'js/deletarVitrine.js' %}" type="text/javascript"></script>
<script src="{% static 'js/deletarProduto.js' %}" type="text/javascript"></script>

<!-- ========================= SECTION CONTENT END// ========================= -->

{% if messages %}
    {% for m in messages %}
        {% if m.level == DEFAULT_MESSAGE_LEVELS.SUCCESS %}
        {{ message }}
        <script>
            Swal.fire({
              position: 'center',
              icon: 'success',
              title: 'Sucesso',
              text:'{{ m }}',
              showConfirmButton: true,
              confirmButtonColor: '#000080',
            })
        </script>
    {% endif %}
    {% endfor %}
{% endif %}
{% endblock %}