apps/ecommerce/urls.py
from django.urls import path

from . import views

app_name = 'e-commerce'

urlpatterns = [
    path('', views.home_page, name='home'),
]

apps/empresas/urls.py
from django.urls import path

from .views.empresa import *
from .views import endereco
from .views import empresa

app_name = 'empresas'

urlpatterns = [
    path('criar-empresa/', CriarEmpresa.as_view(), name='criar_empresa'),
    path('minha-empresa/', empresa.empresa_perfil, name='empresa_perfil'),
    path('deletar-empresa/', empresa.deletar_empresa, name='deletar_empresa'),
    path('editar-empresa/', empresa.editar_empresa, name='editar_empresa'),
    path('empresa/endereco', endereco.empresa_endereco, name='empresa_endereco'),
    path('empresa/endereco/adicionar', endereco.adicionar_endereco, name='empresa_endereco_adicionar'),
    path('empresa/endereco/editar', endereco.editar_endereco, name='editar_endereco'),
    path('empresa/endereco/deletar', endereco.deletar_endereco, name='deletar_endereco'),
    path('empresa/endereco/definir-endereco-padrao', endereco.definir_endereco_padrao, name='definir_endereco_padrao'),
]

apps/produtos/urls.py
from django.urls import path

from apps.produtos.views import *

app_name = 'produtos'

urlpatterns = [
     path('criar-produto/', CriarProduto.as_view(), name='criar_produto'),
     path('ajax/carregar-subcategoria/', carregar_subcategorias, name='ajax_carregar_subcategorias'),
     path('deletar-produto/', deletar_produto, name='deletar_produto'),
     path('editar-produto/', editar_produto, name='editar_produto'),
     path('visualizar-produto/<str:nome>/<int:pk>/', visualizar_produto, name='visualizar_produto'),
]

apps/usuarios/urls.py
from django.urls import path

from .views import usuario
from .views import endereco

app_name = 'usuarios'

urlpatterns = [
    path('cadastro', usuario.SignUp.as_view(), name='cadastrousuario'),
    path('login', usuario.LoginCustomizado.as_view(), name='login'),
    path('resetar-senha', usuario.EmailTokenSenha.as_view(), name='resetarsenha'),
    path('resetar-senha-sucesso-email', usuario.MensagemResetarSenhaEmail.as_view(), name='sucessoresetarsenha'),
    path('reset/<uidb64>/<token>', usuario.ResetarSenha.as_view(), name='novasenha'),
    path('redifinicao-completa', usuario.ResetarSenhaMensagemCompleta.as_view(), name='redifinicaocompleta'),
    path('alterar-senha', usuario.AlteracaoSenha.as_view(), name='alterarsenha'),
    path('criar-perfil', usuario.CriarPerfilUsuario.as_view(), name='criarperfil'),
    path('perfil', usuario.perfil_principal, name='perfil_principal'),
    path('perfil/configuracao', usuario.perfil_configuracao, name='perfil_configuracao'),
    path('perfil/endereco', endereco.perfil_endereco, name='perfil_endereco'),
    path('perfil/endereco/adicionar', endereco.adicionar_endereco, name='perfil_endereco_adicionar'),
    path('perfil/endereco/editar', endereco.editar_endereco, name='editar_endereco'),
    path('perfil/endereco/deletar', endereco.deletar_endereco, name='deletar_endereco'),
    path('perfil/endereco/definir-endereco-padrao', endereco.definir_endereco_padrao, name='definir_endereco_padrao'),
    path('ajax/carregar-cidades/', endereco.carregar_cidades, name='ajax_carregar_cidades'),
    path('ajax/verificar-cep/', endereco.verificar_cep, name='verificar_cep'),
]

apps/vitrines/urls.py
from django.urls import path

from apps.vitrines.views import (
    CriarVitrine,
    listar_vitrine,
    deletar_vitrine,
    editar_vitrine
)

app_name = 'vitrines'

urlpatterns = [
    path('criar-vitrine/', CriarVitrine.as_view(), name='criar_vitrine'),
    path('minha-vitrine/', listar_vitrine, name='minha_vitrine'),
    path('editar-vitrine/', editar_vitrine, name='editar_vitrine'),
    path('deletar-vitrine/', deletar_vitrine, name='deletar_vitrine')
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', include('apps.ecommerce.urls')),
    path('usuarios/', include('apps.usuarios.urls')),
    path('empresas/', include('apps.empresas.urls')),
    path('vitrines/', include('apps.vitrines.urls')),
    path('produtos/', include('apps.produtos.urls')),
    path('pedidos/', include('apps.carrinhos.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/ecommerce/views.py
import logging

from django.shortcuts import render
from django.contrib.auth.decorators import login_required

from apps.usuarios.models import CustomUsuario
from apps.empresas.models import Empresa
from apps.produtos.models import *

# Create your views here.
logger = logging.getLogger(__name__)

def home_page(request):

    usuario = CustomUsuario.objects.filter(email=request.user).first()
    produtos = Produto.objects.order_by('numero_acessos')[:22]
    produtos = list(produtos)
    avaliacoes = Avaliacao.objects.filter(produto__in=produtos).order_by('-nota')
    imagens_produto_recomendados = ImagemProduto.objects.filter(produto__in=produtos)
    produtos = Produto.objects.filter()[:22]
    produtos = list(produtos)
    imagens_produto = ImagemProduto.objects.filter(produto__in=produtos)

    contexto = {
        'usuario': usuario,
        'produtos': produtos,
        'avaliacoes_produto': avaliacoes,
        'imagens_produto': imagens_produto,
        'imagens_produto_recomendados': imagens_produto_recomendados
    }
    return render(request, 'ecommerce/pagina-index.html', contexto)

templates/ecommerce/base.html
<!DOCTYPE HTML>
{% load static %}

<html lang="pt-br">
<head>
<meta charset="utf-8">
<meta http-equiv="pragma" content="no-cache" />
<meta http-equiv="cache-control" content="max-age=604800" />
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

<meta name="description" content="Bootstrap e-commerce html template similar to Alibaba">
<meta name="keywords" content="Online template, shop, theme, template, html, css, bootstrap 4">

<title>Click Reservas</title>

<link href="{% static 'ecommerce/images/mini-logo.png' %}" rel="shortcut icon" type="image/x-icon">

<!-- jQuery -->
<script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.mask/1.14.16/jquery.mask.js"></script>

<script type="text/javascript">
	$(document).ready(function(){
	$('[data-toggle="popover"]').popover();
	});
</script>

<!-- Bootstrap4 files-->
<script src="{% static 'ecommerce/js/bootstrap.bundle.min.js' %}" type="text/javascript"></script>
<link href="{% static 'ecommerce/css/bootstrap.css' %}" rel="stylesheet" type="text/css"/>

<!-- Font awesome 5 -->
<link href="{% static 'ecommerce/fonts/fontawesome/css/all.min.css' %}" type="text/css" rel="stylesheet">

<!-- custom style -->
<link href="{% static 'ecommerce/css/image.css' %}" rel="stylesheet" type="text/css"/>
<link href="{% static 'ecommerce/css/ui.css' %}" rel="stylesheet" type="text/css"/>
<link href="{% static 'ecommerce/css/popover.css' %}" rel="stylesheet" type="text/css"/>
<link href="{% static 'ecommerce/css/responsive.css' %}" rel="stylesheet" type="text/css" />
<link rel="stylesheet" type="text/css" href="{% static 'css/styles.css' %}">
<!-- custom javascript -->
<script src="{% static 'ecommerce/js/script.js' %}" type="text/javascript"></script>

</head>


<header class="section-header">
	<div class="container">
		<nav class="navbar d-none d-md-flex p-md-0 navbar-expand-sm navbar-light border-bottom">
		<div class="container">
		  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTop4" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
		    <span class="navbar-toggler-icon"></span>
		  </button>
		  <div class="collapse navbar-collapse" id="navbarTop4">
		    <ul class="navbar-nav mr-auto">
				{% if not user.is_authenticated %}

        <!-- Mantive a fonte como estava no template original -->
        <li><span class="nav-link"> Olá, clique aqui para
          <a href="{% url 'usuarios:login' %}">
         <strong>Entrar </strong></a>
          ou <a href="{% url 'usuarios:cadastrousuario' %}"> <strong>Registrar-se</strong> </a>
        </span>
        </li>

				{% else %}
				<li><a href="#" class="nav-link"><strong>Ola, seja bem vindo {{ user.first_name }} {{user.last_name}} </strong></a></li>
				<li><a href="{% url 'logout' %}" class="nav-link">
					<img src="https://img.icons8.com/ios-glyphs/26/4a90e2/exit.png"/>
					<strong>
					Sair
					</strong>
				</a>
				</li>
				{% endif %}

		    </ul>
		  </div> <!-- navbar-collapse .// -->
		</div> <!-- container //  -->
		</nav>
	</div>
<section class="header-main border-bottom">
	<div class="container">
		<div class="row align-items-center">
      <!-- deletar essa div -->
			<div class="col-xl-2 col-lg-3 col-md-12">
				<a href="{% url 'e-commerce:home' %}" class="brand-wrap">
					<img class="img-fluid mx-auto d-block" src="{% static 'ecommerce/images/logo.jpeg' %}">
				</a> <!-- brand-wrap.// -->
			</div>
			<div class="col-xl-6 col-lg-5 col-md-6">
				<form action="#" class="search-header">
					<div class="input-group border">
					    <input type="text" class="form-control" placeholder="Procurar">
					    <div class="input-group-append">
					      <button class="btn btn-primary" type="submit">
					        <i class="fa fa-search"></i> Procurar
					      </button>
					    </div>
				    </div>
				</form> <!-- search-wrap .end// -->
			</div> <!-- col.// -->
			<div class="col-xl-4 col-lg-4 col-md-6">
				<div class="widgets-wrap float-md-right">
					<div class="widget-header mr-3">
						<a href="{% url 'usuarios:perfil_principal' %}" class="widget-view">
							<div class="icon-area">
								<i class="fa fa-user"></i>
							</div>

							<small class="text"> Meu perfil </small>

							<small class="text"> Minha conta </small>
						</a>
					</div>
					<div class="widget-header mr-3">
						<a href="#" class="widget-view">
							<div class="icon-area">
								<i class="fa fa-comment-dots"></i>
								<span class="notify">1</span>
							</div>
							<small class="text"> Mensagem </small>
						</a>
					</div>
					<div class="widget-header mr-3">
						<a href="{% url 'pedidos:listar_pedidos' %}" class="widget-view">
							<div class="icon-area">
								<i class="fa fa-store"></i>
							</div>
							<small class="text"> Pedidos </small>
						</a>
					</div>
					<div class="widget-header">
						<a href="{% url 'pedidos:visualizar_carrinho' %}" class="widget-view">
							<div class="icon-area">
								<i class="fa fa-shopping-cart"></i>
							</div>
							<small class="text"> Carrinho </small>
						</a>
					</div>
				</div> <!-- widgets-wrap.// -->
			</div> <!-- col.// -->
		</div> <!-- row.// -->
	</div> <!-- container.// -->
</section> <!-- header-main .// -->



<nav class="navbar navbar-main navbar-expand-lg border-bottom">
<div class="container">
	<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#main_nav" aria-controls="main_nav" aria-expanded="false" aria-label="Toggle navigation">
	<span class="navbar-toggler-icon"></span>
	</button>

	<div class="collapse navbar-collapse" id="main_nav">
	<ul class="navbar-nav">
		<li class="nav-item dropdown">
			<a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#"> <i class="fa fa-bars text-muted mr-2"></i> Navegue aqui </a>
			<div class="dropdown-menu dropdown-large">
				<nav class="row">
					<div class="col-6">
						{% if usuario == None %}
							<a href="{% url 'usuarios:login' %}">Página de login</a>
							<a href="{% url 'usuarios:cadastrousuario' %}">Página de registro</a>
						{% endif %}
						<a href="{% url 'usuarios:perfil_principal' %}"> Meu perfil </a>
						<a href="{% url 'empresas:empresa_perfil' %}"> Minha empresa</a>
						<a href="{% url 'vitrines:minha_vitrine' %}"> Minha vitrine </a>
						<a href="{% url 'usuarios:perfil_endereco' %}"> Meus endereços </a>
						<a href="{% url 'pedidos:listar_pedidos' %}"> Meus pedidos </a>
						<a href="{% url 'pedidos:visualizar_carrinho' %}"> Meu carrinho </a>
				    <a href="page-profile-wishlist.html"> Minha lista de desejos </a>
				    <a href="{% url 'usuarios:perfil_configuracao' %}"> Configurações </a>
					</div>
					<div class="col-6">
						{% if usuario.empresa %}
							<a href="{% url 'empresas:empresa_endereco' %}"> Endereços da empresa </a>
							<a href="#!"> Pedidos em espera </a>
							<a href="#!"> Minha lista de vendas </a>
							<a href="#!"> Meus itens de venda </a>
							<a href="{% url 'empresas:editar_empresa' %}"> Configurações da empresa </a>
				    {% else %}
							<a href="#!" data-toggle="popover" data-content="Empresa não cadastrada"
							 	data-placement="right"> Endereços da empresa</a>
				      <a href="#!" data-toggle="popover" data-content="Empresa não cadastrada"
							 	data-placement="right"> Pedidos em espera </a>
				      <a href="#!" data-toggle="popover" data-content="Empresa não cadastrada"
							 	data-placement="right"> Minha lista de vendas </a>
							<a href="#!" data-toggle="popover" data-content="Empresa não cadastrada"
								data-placement="right"> Meus itens de vendas </a>
				      <a href="#!" data-toggle="popover" data-content="Empresa não cadastrada"
							 	data-placement="right"> Configurações da empresa </a>
				    {% endif %}
						{% if usuario %}
							<a href="{% url 'logout' %}"> Sair </a>
						{% endif %}
					</div>
				</nav> <!--  row end .// -->
			</div> <!--  dropdown-menu dropdown-large end.// -->
		</li>
		<li class="nav-item">
		<a class="nav-link" href="#">Categorias</a>
		</li>
		<li class="nav-item">
		<a class="nav-link" href="{% url 'pedidos:listar_pedidos' %}">Histórico de compras</a>
		</li>
		<li class="nav-item">
		<a class="nav-link" href="{% url 'vitrines:minha_vitrine' %}">Venda conosco</a>
	</li>
	<li class="nav-item">
	<a class="nav-link" href="#!"data-toggle="popover" data-content="Função em desenvolvimento" data-placement="bottom">Contato</a>
	</li>
	</ul>
	</div> <!-- collapse .// -->
</div> <!-- container .// -->
</nav>

</header> <!-- section-header.// -->

{% block body %}
{% endblock %}

<!-- ========================= FOOTER ========================= -->
<footer class="section-footer bg-secondary">
	<div class="container">
		<section class="footer-top padding-y-lg text-white">
			<div class="row">
				<aside class="col-md col-6">
					<h6 class="title">Marcas</h6>
					<ul class="list-unstyled">
						<li> <a href="#">Adidas</a></li>
						<li> <a href="#">Puma</a></li>
						<li> <a href="#">Reebok</a></li>
						<li> <a href="#">Nike</a></li>
					</ul>
				</aside>
				<aside class="col-md col-6">
					<h6 class="title">Empresa</h6>
					<ul class="list-unstyled">
						<li> <a href="#">Sobre nós</a></li>
						<li> <a href="#">Carreira</a></li>
						<li> <a href="#">Sobre o site</a></li>
						<li> <a href="#">Regras e termos</a></li>
						<li> <a href="#">Mapa do site</a></li>
					</ul>
				</aside>
				<aside class="col-md col-6">
					<h6 class="title">Ajuda</h6>
					<ul class="list-unstyled">
						<li> <a href="#">Nosso contato</a></li>
						<li> <a href="#">devolução de dinheiro</a></li>
						<li> <a href="#">Status dos pedidos</a></li>
						<li> <a href="#">Informação de Envio</a></li>
						<!-- <li> <a href="#">Open dispute</a></li> -->
					</ul>
				</aside>
				<aside class="col-md col-6">
					<h6 class="title">Conta</h6>
					<ul class="list-unstyled">
						<li> <a href="{% url 'usuarios:login' %}"> Login de usuário </a></li>
						<li> <a href="{% url 'usuarios:cadastrousuario' %}"> Registro de usuário </a></li>
						<li> <a href="{% url 'usuarios:perfil_configuracao' %}"> Configurações da conta </a></li>
						<li> <a href="{% url 'pedidos:visualizar_carrinho' %}"> Meus pedidos </a></li>
					</ul>
				</aside>
				<aside class="col-md">
					<h6 class="title">Social</h6>
					<ul class="list-unstyled">
						<li><a href="#"> <i class="fab fa-facebook"></i> Facebook </a></li>
						<li><a href="#"> <i class="fab fa-twitter"></i> Twitter </a></li>
						<li><a href="#"> <i class="fab fa-instagram"></i> Instagram </a></li>
						<li><a href="#"> <i class="fab fa-youtube"></i> Youtube </a></li>
					</ul>
				</aside>
			</div> <!-- row.// -->
		</section>	<!-- footer-top.// -->

		<section class="footer-bottom text-center">

				<p class="text-white">Política de privacidade - Termos de uso - Informações do usuário Guia de consulta jurídica</p>
				<p class="text-muted"> &copy 2021 Click Reservas, Todos os direitos reservados </p>
				<br>
		</section>
	</div><!-- //container -->
</footer>
<!-- ========================= FOOTER END // ========================= -->

</html>

templates/ecommerce/pagina-index.html
{% extends 'ecommerce/base.html' %}
{% load static %}

{% block body %}

<body>

<!-- ========================= SECTION MAIN  ========================= -->
<section class="section-intro padding-y">
<div class="container">
<!-- ================== COMPONENT SLIDER  BOOTSTRAP  ==================  -->
<div id="carousel1_indicator" class="slider-home-banner carousel slide" data-ride="carousel">
  <ol class="carousel-indicators">
    <li data-target="#carousel1_indicator" data-slide-to="0" class="active"></li>
    <li data-target="#carousel1_indicator" data-slide-to="1"></li>
    <li data-target="#carousel1_indicator" data-slide-to="2"></li>
  </ol>
  <div class="carousel-inner">
    <div class="carousel-item active">
      <img src="{% static 'ecommerce/images/banners/slide1.jpg' %}" alt="First slide">
    </div>
    <div class="carousel-item">
      <img src="{% static 'ecommerce/images/banners/slide2.jpg' %}" alt="Second slide">
    </div>
    <div class="carousel-item">
      <img src="{% static 'ecommerce/images/banners/slide3.jpg' %}" alt="Third slide">
    </div>
  </div>
  <a class="carousel-control-prev" href="#carousel1_indicator" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carousel1_indicator" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>
<!-- ==================  COMPONENT SLIDER BOOTSTRAP end.// ==================  .// -->

</div> <!-- row.// -->
</section>
<!-- ========================= SECTION MAIN END// ========================= -->

<!-- =============== SECTION ITEMS =============== -->
<section  class="padding-bottom-sm">

<header class="section-heading heading-line">
	<h4 class="title-section text-uppercase ml-3">Produtos recomendados</h4>
</header>

<div class="row row-sm">
  {% for recomendado in avaliacoes_produto %}
    <div class="col-xl-2 col-lg-3 col-md-4 col-6 ml-1">
      <div class="card card-sm card-product-grid">
        <div class="img-wrap">
    {% for imagem in imagens_produto_recomendados %}
      {% if imagem.produto == recomendado.produto %}
          <a href="{% url 'produtos:visualizar_produto' nome=recomendado.produto.nome pk=recomendado.produto.pk %}">
            <img class="zoom" src="{{ imagem.imagem.url }}">
          </a>
        <!-- </form> -->
      {% endif %}
    {% endfor %}
        </div>
        <figcaption class="info-wrap">

          <a href="{% url 'produtos:visualizar_produto' nome=recomendado.produto.nome pk=recomendado.produto.pk %}" class="title">
            {{ recomendado.produto.nome }}
          </a>
          <div class="price mt-1"> R$ {{ recomendado.produto.preco }}</div> <!-- price-wrap.// -->
        </figcaption>
      </div>
    </div> <!-- col.// -->
    {% if avaliacoes_produto is empty %}
      <div class="alert alert-warning mt-3">
        <p class="icontext"> Nenhum produto recomendado </p>
      </div>
    {% endif %}
  {% endfor %}

  </div> <!-- row.// -->
</section>

<section  class="padding-bottom-sm">

<header class="section-heading heading-line">
	<h4 class="title-section text-uppercase ml-3">Produtos Gerais</h4>
</header>

<div class="row row-sm">
  {% for produto in produtos %}
    <div class="col-xl-2 col-lg-3 col-md-4 col-6 ml-1">
      <div class="card card-sm card-product-grid">
        <div class="img-wrap">
    {% for imagem in imagens_produto %}
      {% if imagem.produto == produto %}
          <a href="{% url 'produtos:visualizar_produto' nome=produto.nome pk=produto.pk %}">
            <img class="zoom" src="{{ imagem.imagem.url }}">
          </a>
      {% endif %}
    {% endfor %}
        </div>
        <figcaption class="info-wrap">
          <a href="{% url 'produtos:visualizar_produto' nome=produto.nome pk=produto.pk %}" class="title">
            {{ produto.nome }}
          </a>
          <div class="price mt-1"> R$ {{ produto.preco }}</div> <!-- price-wrap.// -->
        </figcaption>
      </div>
    </div> <!-- col.// -->

    {% if produtos is empty %}
      <div class="alert alert-warning mt-3">
        <p class="icontext"> Nenhum produto adicionado </p>
      </div>
    {% endif %}
  {% endfor %}

  </div> <!-- row.// -->
</section>
<!-- =============== SECTION ITEMS .//END =============== -->


<!-- =============== SECTION SERVICES =============== -->
<section  class="padding-bottom">

<header class="section-heading heading-line">
	<h4 class="title-section text-uppercase">Serviços comerciais</h4>
</header>

<div class="row">
	<div class="col-md-3 col-sm-6">
		<article class="card card-post">
		  <img src="images/posts/1.jpg" class="card-img-top">
		  <div class="card-body">
		    <h6 class="title">Trade Assurance</h6>
		    <p class="small text-uppercase text-muted">Order protection</p>
		  </div>
		</article> <!-- card.// -->
	</div> <!-- col.// -->
	<div class="col-md-3 col-sm-6">
		<article class="card card-post">
		  <img src="images/posts/2.jpg" class="card-img-top">
		  <div class="card-body">
		    <h6 class="title">Pay anytime</h6>
		    <p class="small text-uppercase text-muted">Finance solution</p>
		  </div>
		</article> <!-- card.// -->
	</div> <!-- col.// -->
	<div class="col-md-3 col-sm-6">
		<article class="card card-post">
		  <img src="images/posts/3.jpg" class="card-img-top">
		  <div class="card-body">
		    <h6 class="title">Inspection solution</h6>
		    <p class="small text-uppercase text-muted">Easy Inspection</p>
		  </div>
		</article> <!-- card.// -->
	</div> <!-- col.// -->
	<div class="col-md-3 col-sm-6">
		<article class="card card-post">
		  <img src="images/posts/4.jpg" class="card-img-top">
		  <div class="card-body">
		    <h6 class="title">Ocean and Air Shipping</h6>
		    <p class="small text-uppercase text-muted">Logistic services</p>
		  </div>
		</article> <!-- card.// -->
	</div> <!-- col.// -->
</div> <!-- row.// -->

</section>
<!-- =============== SECTION SERVICES .//END =============== -->

<article class="my-4">
	<img src="{% static 'ecommerce/images/banners/ad-sm.png' %}" class="w-100">
</article>
</div>
<!-- container end.// -->

<!-- ========================= SECTION SUBSCRIBE  ========================= -->
<section class="section-subscribe padding-y-lg">
<div class="container">

<p class="pb-2 text-center text-white">
	Entregando as últimas tendências de produtos e notícias do setor diretamente na sua caixa de entrada
</p>

<div class="row justify-content-md-center">
	<div class="col-lg-5 col-md-6">
<form class="form-row">
		<div class="col-md-8 col-7">
		<input class="form-control border-0" placeholder="Seu e-mail" type="email">
		</div> <!-- col.// -->
		<div class="col-md-4 col-5">
		<button type="submit" class="btn btn-block btn-warning"> <i class="fa fa-envelope"></i> Inscrever-se </button>
		</div> <!-- col.// -->
</form>
<small class="form-text text-white-50">Nunca compartilharemos seu endereço de e-mail com terceiros. </small>
	</div> <!-- col-md-6.// -->
</div>


</div>
</section>
<!-- ========================= SECTION SUBSCRIBE END// ========================= -->

</body>

<style media="screen">
body {
   height: 100%;
   overflow-x: hidden;
}
</style>


{% endblock %}