apps/empresas/urls.py
from django.urls import path

from .views.empresa import *
from .views import endereco
from .views import empresa

app_name = 'empresas'

urlpatterns = [
    path('criar-empresa/', CriarEmpresa.as_view(), name='criar_empresa'),
    path('minha-empresa/', empresa.empresa_perfil, name='empresa_perfil'),
    path('deletar-empresa/', empresa.deletar_empresa, name='deletar_empresa'),
    path('editar-empresa/', empresa.editar_empresa, name='editar_empresa'),
    path('empresa/endereco', endereco.empresa_endereco, name='empresa_endereco'),
    path('empresa/endereco/adicionar', endereco.adicionar_endereco, name='empresa_endereco_adicionar'),
    path('empresa/endereco/editar', endereco.editar_endereco, name='editar_endereco'),
    path('empresa/endereco/deletar', endereco.deletar_endereco, name='deletar_endereco'),
    path('empresa/endereco/definir-endereco-padrao', endereco.definir_endereco_padrao, name='definir_endereco_padrao'),
]

apps/usuarios/urls.py
from django.urls import path

from .views import usuario
from .views import endereco

app_name = 'usuarios'

urlpatterns = [
    path('cadastro', usuario.SignUp.as_view(), name='cadastrousuario'),
    path('login', usuario.LoginCustomizado.as_view(), name='login'),
    path('resetar-senha', usuario.EmailTokenSenha.as_view(), name='resetarsenha'),
    path('resetar-senha-sucesso-email', usuario.MensagemResetarSenhaEmail.as_view(), name='sucessoresetarsenha'),
    path('reset/<uidb64>/<token>', usuario.ResetarSenha.as_view(), name='novasenha'),
    path('redifinicao-completa', usuario.ResetarSenhaMensagemCompleta.as_view(), name='redifinicaocompleta'),
    path('alterar-senha', usuario.AlteracaoSenha.as_view(), name='alterarsenha'),
    path('criar-perfil', usuario.CriarPerfilUsuario.as_view(), name='criarperfil'),
    path('perfil', usuario.perfil_principal, name='perfil_principal'),
    path('perfil/configuracao', usuario.perfil_configuracao, name='perfil_configuracao'),
    path('perfil/endereco', endereco.perfil_endereco, name='perfil_endereco'),
    path('perfil/endereco/adicionar', endereco.adicionar_endereco, name='perfil_endereco_adicionar'),
    path('perfil/endereco/editar', endereco.editar_endereco, name='editar_endereco'),
    path('perfil/endereco/deletar', endereco.deletar_endereco, name='deletar_endereco'),
    path('perfil/endereco/definir-endereco-padrao', endereco.definir_endereco_padrao, name='definir_endereco_padrao'),
    path('ajax/carregar-cidades/', endereco.carregar_cidades, name='ajax_carregar_cidades'),
    path('ajax/verificar-cep/', endereco.verificar_cep, name='verificar_cep'),
]

apps/vitrines/urls.py
from django.urls import path

from apps.vitrines.views import (
    CriarVitrine,
    listar_vitrine,
    deletar_vitrine,
    editar_vitrine
)

app_name = 'vitrines'

urlpatterns = [
    path('criar-vitrine/', CriarVitrine.as_view(), name='criar_vitrine'),
    path('minha-vitrine/', listar_vitrine, name='minha_vitrine'),
    path('editar-vitrine/', editar_vitrine, name='editar_vitrine'),
    path('deletar-vitrine/', deletar_vitrine, name='deletar_vitrine')
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', include('apps.ecommerce.urls')),
    path('usuarios/', include('apps.usuarios.urls')),
    path('empresas/', include('apps.empresas.urls')),
    path('vitrines/', include('apps.vitrines.urls')),
    path('produtos/', include('apps.produtos.urls')),
    path('pedidos/', include('apps.carrinhos.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/empresas/models.py
import os
from uuid import uuid4

from django.db import models
from stdimage import StdImageField

from apps.empresas.validadoresForm import validar_cnpj


def adicionar_imagem_logo(instance, filename):
    ext = filename.split('.')[-1]
    filename = '{}.{}'.format(uuid4().hex, ext)
    return os.path.join('logoEmpresa/', filename)


class Empresa(models.Model):
    razaoSocial = models.CharField('Razão social', max_length=60, help_text='Obrigatório')
    fantasia = models.CharField('Nome fantasia', max_length=60, help_text='Obrigatório')
    cnpj = models.CharField('CNPJ', max_length=18, help_text='Obrigatório', validators=[validar_cnpj])
    inscricaoEstadual = models.CharField('Inscrição Estadual', max_length=50, null=True, blank=True,
                                         help_text='Não obrigatório')
    inscricaoMunicipal = models.CharField('Inscrição Municipal', max_length=50, null=True, blank=True,
                                          help_text='Não obrigatório')
    logo = StdImageField('Logo da empresa', upload_to=adicionar_imagem_logo, null=True, help_text='Obrigatório')
    status = models.BooleanField('Ativo?', default=True)

    class Meta:
        verbose_name = 'Empresa'
        verbose_name_plural = 'Empresas'

    def __str__(self):
        return '{} - {} - {}'.format(self.cnpj, self.razaoSocial, self.fantasia)

apps/empresas/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic import (
    CreateView,
    ListView
)
from .forms import CadastroEmpresa, EditarEmpresaForm

from .models import Empresa
from apps.usuarios.models import CustomUsuario

recuperar_id_empresa_editar = {}
recuperar_id_empresa_deletar = {}

from validate_docbr import CNPJ


# Metodo para retornar se existe uma empresa ativa ou não
def consulta_empresa(empresa):
    if empresa is None:
        query_set = Empresa.objects.none()
    else:
        query_set = Empresa.objects.filter(cnpj=empresa.cnpj, status=True)
    return query_set


def cnpj_sem_formatacao(cnpj):
    cnpj_cortado_digitos_finais = str(cnpj).split('-')
    cnpj_cortado_digitos_iniciais = cnpj_cortado_digitos_finais[0].split('.')
    cnpj_cortado_digitos_meio = ''
    aux_cnpj_sem_formatacao = ''
    tamanho_lista_digito_inicial = len(cnpj_cortado_digitos_iniciais)

    for i in range(0, tamanho_lista_digito_inicial, 1):
        if i != 2:
            aux_cnpj_sem_formatacao = aux_cnpj_sem_formatacao + cnpj_cortado_digitos_iniciais[i]
        elif i == 2:
            cnpj_cortado_digitos_meio = cnpj_cortado_digitos_iniciais[i].split('/')

    tamanho_lista_digito_meio = len(cnpj_cortado_digitos_meio)

    for i in range(0, tamanho_lista_digito_meio, 1):
        aux_cnpj_sem_formatacao += cnpj_cortado_digitos_meio[i]

    aux_cnpj_sem_formatacao += cnpj_cortado_digitos_finais[1]
    return aux_cnpj_sem_formatacao


@login_required(login_url='/usuarios/login')
def delecao_empresa(request):
    if len(request.POST) == 2:
        empresa = get_object_or_404(Empresa, pk=request.POST.get('id'))
        recuperar_id_empresa_deletar['empresa'] = empresa
        empresa.status = False
        empresa.save()
    if not recuperar_id_empresa_deletar['empresa'].status:
        messages.success(request, 'Empresa deletada com sucesso!')

    return redirect('empresas:listar_empresas')


class CriarEmpresa(LoginRequiredMixin, CreateView):
    login_url = '/usuarios/login'

    def get(self, request, *args, **kwargs):
        form = super().get_form(CadastroEmpresa)
        empresa = self.request.user.empresa
        query_set = consulta_empresa(empresa)
        usuario_logado = CustomUsuario.objects.get(email=request.user)

        context = {
            'form': form,
            'empresa': query_set,
            'usuario': usuario_logado
        }
        return render(request, 'empresas/empresa_cadastro.html', context)

    def post(self, request, *args, **kwargs):
        form = self.get_form(CadastroEmpresa)

        if form.is_valid():
            razaoSocial = form.cleaned_data['razaoSocial']
            nomeFantasia = form.cleaned_data['fantasia']
            inscricaoEstadual = form.cleaned_data['inscricaoEstadual']
            inscricaoMunicipal = form.cleaned_data['inscricaoMunicipal']
            logo = form.cleaned_data['logo']
            cnpj = form.cleaned_data['cnpj']

            if cnpj:
                if len(cnpj) == 18:
                    cnpj = cnpj_sem_formatacao(cnpj)
                else:
                    messages.error(request, 'CNPJ inválido')
            else:
                messages.error(request, 'CNPJ inválido')

            empresa = Empresa.objects.create(cnpj=cnpj, razaoSocial=razaoSocial,
                                             fantasia=nomeFantasia, inscricaoEstadual=inscricaoEstadual,
                                             inscricaoMunicipal=inscricaoMunicipal, logo=logo)
            usuario = self.request.user
            usuario_bd = CustomUsuario.objects.get(email=usuario.email)
            usuario_bd.empresa = empresa
            usuario_bd.save()

            return redirect('empresas:listar_empresas')

        else:
            messages.error(request, 'Erro ao enviar o formulário !')

        context = {
            'form': form
        }

        return render(request, 'empresas/empresa_cadastro.html', context)


class ListarEmpresa(LoginRequiredMixin, ListView):
    login_url = '/usuarios/login'
    model = Empresa
    template_name = 'empresas/empresa_listar.html'
    context_object_name = 'empresas'

    def get_queryset(self):
        empresa = self.request.user.empresa
        query_set = consulta_empresa(empresa)
        return query_set


@login_required(login_url='/usuarios/login')
def edicao_empresa(request):
    usuario = CustomUsuario.objects.get(email=request.user)
    form = EditarEmpresaForm(request.POST or None)

    if len(request.POST) == 2:
        if not recuperar_id_empresa_editar:
            recuperar_id_empresa_editar['id'] = request.POST.get('id')
    empresa = retornar_empresa()

    if str(request.method) == 'POST':
        if len(request.POST) > 2:
            form = EditarEmpresaForm(request.POST, instance=empresa)
            cnpj = CNPJ()

            aux_cnpj = request.POST.get('cnpj')
            resultado_validacao = cnpj.validate(aux_cnpj)

            if not resultado_validacao:
                messages.error(request, 'CNPJ inválido')

            if form.is_valid():
                razaoSocial = form.cleaned_data['razaoSocial']
                nomeFantasia = form.cleaned_data['fantasia']
                inscricaoEstadual = form.cleaned_data['inscricaoEstadual']
                inscricaoMunicipal = form.cleaned_data['inscricaoMunicipal']
                cnpj = form.cleaned_data['cnpj']

                if cnpj:
                    if len(cnpj) == 18:
                        cnpj = cnpj_sem_formatacao(cnpj)
                    else:
                        messages.error(request, 'CNPJ inválido')
                else:
                    messages.error(request, 'CNPJ inválido')

                empresa.razaoSocial = razaoSocial
                empresa.fantasia = nomeFantasia
                empresa.inscricaoEstadual = inscricaoEstadual
                empresa.inscricaoMunicipal = inscricaoMunicipal
                empresa.cnpj = cnpj

                empresa.save()
                messages.success(request, 'Empresa editada com sucesso!')
                return redirect('empresas:listar_empresas')

    form = EditarEmpresaForm(instance=empresa)

    context = {
        'usuario': usuario,
        'form': form,
        'editar': 'editar'

    }

    return render(request, 'empresas/empresa_cadastro.html', context)


def retornar_empresa():
    if recuperar_id_empresa_editar:
        empresa = get_object_or_404(Empresa, pk=recuperar_id_empresa_editar['id'])
        return empresa

apps/empresas/views/endereco.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect, get_object_or_404

from ..models import Empresa
from ...usuarios.models import Telefone, Endereco
from apps.usuarios.models import CustomUsuario
from apps.usuarios.forms import EnderecoForm
from apps.usuarios.views.endereco import (
    verificar_endereco_adicionar,
    verificar_endereco_editar,
    buscar_estados_api,
    buscar_cidades_api
)

@login_required(login_url='/usuarios/login')
def empresa_endereco(request):

    enderecos = Endereco.objects.filter(usuario=request.user, empresa=request.user.empresa, status=True)

    contexto = {
        'enderecos': enderecos,
        'usuario': request.user
    }
    return render(request, 'empresas/endereco/empresa-endereco.html', contexto)

@login_required(login_url='/usuarios/login')
def adicionar_endereco(request):

    if request.method == "POST":

        endereco = verificar_endereco_adicionar(request.POST['estado'],
            request.POST['cidade'],
            request.POST['cep'],
            request.POST['bairro'],
            request.POST['rua'],
            request.POST['numero'],
            request.POST['complemento']
        )

        if endereco != '':
            endereco.usuario = request.user
            endereco.empresa = request.user.empresa

            # verifica se é o primeiro endereco, se sim torna-lo padrao
            enderecos = Endereco.objects.filter(usuario=request.user, empresa=request.user.empresa, status=True)
            if len(enderecos) == 0:
                endereco.padrao = True

            endereco.save()

            return redirect('empresas:empresa_endereco')
    else:
        form = EnderecoForm()

    estados = buscar_estados_api()
    contexto = {
        'form': form,
        'estados': estados,
        'usuario': request.user
    }

    return render(request, 'empresas/endereco/empresa-endereco-adicionar.html', contexto)

@login_required(login_url='/usuarios/login')
def editar_endereco(request):
    endereco = get_object_or_404(Endereco, pk=request.POST['endereco'])

    if len(request.POST) > 2:

        endereco = verificar_endereco_editar(request.POST['endereco'],
            request.POST['estado'],
            request.POST['cidade'],
            request.POST['cep'],
            request.POST['bairro'],
            request.POST['rua'],
            request.POST['numero'],
            request.POST['complemento']
        )

        return redirect('empresas:empresa_endereco')

    else:
        cidades = buscar_cidades_api(endereco.estado.sigla)
        nome_cidades = list(cidades.values())
        estados = buscar_estados_api()
        contexto = {
            'endereco': endereco,
            'estados': estados,
            'cidades': nome_cidades,
            'usuario': request.user
        }

        return render(request, 'empresas/endereco/empresa-endereco-editar.html', contexto)

@login_required(login_url='/usuarios/login')
def deletar_endereco(request):
    endereco = get_object_or_404(Endereco, pk=request.POST['endereco'])
    era_padrao = endereco.padrao
    endereco.padrao = False
    endereco.status = False
    endereco.save()

    if era_padrao:
        enderecos = Endereco.objects.filter(usuario=request.user, empresa=request.user.empresa, status=True)

        # se o endereço deletado era padrão e houver outro, trocar automaticamente
        if len(enderecos) > 0:
            endereco = get_object_or_404(Endereco, pk=enderecos[0].pk)
            endereco.padrao = True
            endereco.save()

    return redirect('empresas:empresa_endereco')

@login_required(login_url='/usuarios/login')
def definir_endereco_padrao(request):
    enderecos = Endereco.objects.filter(usuario=request.user, empresa=request.user.empresa, padrao=True)

    if len(enderecos) > 0:
        endereco = get_object_or_404(Endereco, pk=enderecos[0].pk)
        endereco.padrao = False
        endereco.save()

    endereco = get_object_or_404(Endereco, pk=request.POST['endereco'])
    endereco.padrao = True
    endereco.save()

    return redirect('empresas:empresa_endereco')

templates/empresas/empresa_cadastro.html
{% extends 'usuarios/perfil-principal.html' %}

{% load static %}
{% load crispy_forms_tags %}

{% block content %}


<main class="col-md-9">
    <div class="card mb-4">
      <div class="card-body ">

          {% if not usuario.status %}
          <div>
              <h5 class="text-center mt-4">
                  <strong>
					 Você precisa realizar o cadastro de seu perfil para adicionar a sua empresa
                  </strong>
                  <img src="{% static 'ecommerce/images/atencao.png' %}"/>
                  </h5>
					<div class="d-flex justify-content-center">

				<a href="{% url 'usuarios:criarperfil' %}" class="btn btn-secondary">Cadastrar perfil</a>
					</div>
				</div>

				{% elif usuario.status %}
                                      {% if not empresa %}

              <h4 class="card-title mb-5">
                {% if editar == 'editar' %}
                    Editar empresa

                    {% else %}
                  Cadastrar empresa
                    {% endif %}
                </h4>

          {% if messages %}
            {% for message in messages %}
                {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}
                    <div class="alert alert-danger " role="alert">
                        {{ message }}
                    </div>
                {% endif %}
    {% endfor %}
{% endif %}
  <div class="col-lg-8">

    <form  method="POST" name="editar" autocomplete="off" enctype="multipart/form-data" onsubmit="return validateForm()">
      {% csrf_token %}
      <div class="form-row">
        <div class="form-group col-md-6">
          {{ form.razaoSocial|as_crispy_field }}
        </div>
        <div class="form-group col-md-6">
          {{ form.fantasia|as_crispy_field }}
        </div>
      </div>
      <div class="form-row">
        <div class="form-group col-md-6">
          {{ form.cnpj|as_crispy_field }}
        </div>
        <div class="form-group col-md-6">
          {{ form.inscricaoMunicipal|as_crispy_field }}
        </div>

          <div class="form-group col-md-6">
            <div class="container">
              <div class="row">
                  <div class="col-md-12">
                    <label>Inscrição Estadual</label>
                  </div>
                  <div class="col-lg-4 col-sm-4">
                    <select id="estado" name="estado" >
                      <option value="" disabled selected hidden>-</option>
                      {% for indice, estado in estados.items %}
                      <option value="{{ estado.sigla }}">
                        {{ estado.sigla }}
                      </option>
                      {% endfor %}
                    </select>
                  </div>
                <div class="col-lg-8">
                  {{ form.inscricaoEstadual|as_crispy_field }}
                </div>
              </div>
            </div>
          </div>
          {% include "usuarios/telefone-formulario.html" %}
          <div class="form-group col-md-6">
            {% if not editar == 'editar' %}
              <label class="col-md" for="foto">Logo</label>
              <label class="btn btn-info" for="foto">
                  <input id="foto" name="logo" type="file" style="display:none"
                    onchange="$(`#nome-foto`).text(this.files[0].name)" accept='image/*' required>
                  Selecione a imagem
              </label>
              <span class='label label-info' id="nome-foto"></span>
              <div class="col-md">
                <small class="col-md form-text text-muted">Obrigatório</small>
              </div>
            {% endif %}
          </div>
        </div>

      </div>
      <div class="form-group">
        <a href="{% url 'usuarios:perfil_principal' %}" class="btn btn-secondary float-right">Voltar para meu perfil
          <i class="fas fa-arrow-circle-left"></i>
        </a>

        <button type="submit" class="btn btn-primary"> Salvar </button>
      </div>
    </form>
  </div>
                  {% elif empresa %}
            <div class="d-flex justify-content-center">
                          <h5>
                    <strong>Você já possui uma empresa!</strong>
                </h5>
            </div>
                  <div class="d-flex justify-content-center">
                 <br>
        <a href="{% url 'empresas:listar_empresas' %}" class="btn btn-secondary mb-3 float-right" >Ir para minha empresa <i class="fas fa-arrow-circle-right"></i>

        </a>
            </div>
                  {% endif %}


                {% endif %}


          {% if messages %}

{% endif %}

      </div>
    </div>
</main>

<script src="https://cdn.jsdelivr.net/npm/sweetalert2@10"></script>
<script src="{% static 'js/mascaraIM.js' %}" type="text/javascript"></script>
<script src="{% static 'js/mascaraIE.js' %}" type="text/javascript"></script>
<script src="{% static 'js/validarIE.js' %}" type="text/javascript"></script>
<script src="{% static 'js/validarCNPJ.js' %}" type="text/javascript"></script>
<script src="{% static 'js/validarFoto.js' %}" type="text/javascript"></script>
<script src="{% static 'js/validarTelefone.js' %}" type="text/javascript"></script>
<script src="{% static 'js/adicionarEmpresaMascara.js' %}" type="text/javascript"></script>


	{% if messages %}
		{% for m in messages %}
		<script>


			{% if m.level == DEFAULT_MESSAGE_LEVELS.ERROR %}

				const Toast = Swal.mixin({
				  toast: true,
				  position: 'center',
				  showConfirmButton: true,
				  timer: 3000,
				  timerProgressBar: true,
				  didOpen: (toast) => {
					toast.addEventListener('mouseenter', Swal.stopTimer)
					toast.addEventListener('mouseleave', Swal.resumeTimer)
				  }
				})

				Toast.fire({
				  icon: 'error',
				  title: 'Erro ao enviar formulário!\n'+'{{m}}'
				}).then((result) => {
				  if (result.isConfirmed) {
				  }
				})
				{% endif %}
		  </script>
		{% endfor %}
	{% endif %}

{% endblock %}

templates/empresas/empresa_perfil.html
{% extends 'usuarios/perfil-principal.html' %}
{% load static %}
{% block content %}

<body xmlns="http://www.w3.org/1999/html">

<main class="col-md-9">

      {% if not empresa %}
        <div class="d-flex justify-content-center">
            <h5>
                <strong>Você não cadastrou a sua empresa!</strong>
            </h5>
            <br>

        </div>
        <div class="d-flex justify-content-center">
             <br>
                <a href="{% url 'empresas:criar_empresa' %}" class="btn btn-secondary mb-3" ><i class="fa fa-plus"></i> Adicionar nova empresa</a>
        </div>
        {% else %}
          <main class="col-md-12">
            <article class="card mb-3">

              <div class="container">
                <div class="row">
                  <figure class="icontext">
                    <div class="icon">
                      <img class="rounded-circle img-sm" src="{{ empresa.logo.url }}">
                    </div>
                  </figure>
                  <div class="col-lg-4 col-md-6">
                    <strong> Nome fantasia: </strong> {{ empresa.fantasia }} <br>
                    <strong> Razão Social: </strong> {{ empresa.razaoSocial }} <br>
                    <strong> CNPJ: </strong> {{ empresa.cnpj }} <br>
                    <button class="btn btn-light btn-sm" data-toggle="modal" data-target="#modal-foto">Alterar logo</button>

                    {% include 'usuarios/modal-foto.html' %}

                  </div>
                  <div class="col-lg-6">
                    {% if empresa.inscricaoEstadual is None %}
                    <strong> Inscrição estadual: </strong> Sem inscrição estadual <br>
                    {% else %}
                    <strong> Inscrição estadual: </strong> {{ empresa.inscricaoEstadual }} <br>
                    {% endif %}
                    {% if empresa.inscricaoMunicipal is None %}
                    <strong> Inscrição municipal: </strong> Sem inscrição municipal <br>
                    {% else %}
                    <strong> Inscrição estadual: </strong> {{ empresa.inscricaoMunicipal }} <br>
                    {% endif %}
                  </div>
                </div>
              </div>
              <hr>
              <div class="container">
                <div class="row">
                  <div class="col-lg-7">
                    <p>
                      <i class="fa fa-map-marker text-muted"></i> &nbsp; Endereços da empresa:
                      <br>
                      <div class="form-inline">
                        {% for endereco in enderecos %}
                        {{ endereco.cidade.nome }}, {{ endereco.rua }},
                        {{ endereco.bairro }}, {{ endereco.numero}} &nbsp
                        <form action="{% url 'usuarios:editar_endereco' %}"  method="post">
                          {% csrf_token %}
                          <button type="submit" class="btn btn-light btn-sm" name="endereco"
                          value="{{ endereco.pk }}" style="background-color:white; border-color:white;">
                          Editar
                        </button>
                      </form>
                      <br>
                      {% empty %}
                      <p> Sua empresa ainda não possui nenhum endereço </p>
                      {% endfor %}
                    </div>
                  </p>
                  <br>
                </div>
                <div class="col-lg-5">
                  <p>
                    <i class="fas fa-phone text-muted"></i> &nbsp; Telefones da empresa:
                    <br>
                    <div class="form-inline">
                      {% for telefone in telefones %}
                      {{ telefone.tipo }}: {{ telefone.numero }} &nbsp
                      <form action="#"  method="post">
                        {% csrf_token %}
                        <button type="submit" class="btn btn-light btn-sm" name="endereco"
                        value="{{ endereco.pk }}" style="background-color:white; border-color:white;">
                        Editar
                      </button>
                    </form>
                    <br>
                    {% empty %}
                    <p> A empresa ainda não possui nenhum telefone </p>
                    {% endfor %}
                  </div>
                </p>
              </div>
            </div>
          </div>
        </article>
      </main>

      <article class="card-group card-stat">
        <figure class="card bg">
          <div class="p-3">
            <h4 class="title">38</h4>
            <span>Pedidos em espera</span>
          </div>
        </figure>
        <figure class="card bg">
          <div class="p-3">
            <h4 class="title">12</h4>
            <span>Aguardando entrega</span>
          </div>
        </figure>
        <figure class="card bg">
          <div class="p-3">
            <h4 class="title">50</h4>
            <span>Produtos e serviços entregues</span>
          </div>
        </figure>
      </article>
    </div>
  {% endif %}
  </main>

<script src="https://cdn.jsdelivr.net/npm/sweetalert2@10"></script>

</body>
<script src="{% static 'js/mensagemDeletarEmpresa.js' %}" type="text/javascript"></script>
<script src="{% static 'js/editarEmpresa.js' %}" type="text/javascript"></script>
<script src="{% static 'js/validarFoto.js' %}" type="text/javascript"></script>

{% if messages %}
  <ul class="messages">
      {% for m in messages %}
          {% if m.level == DEFAULT_MESSAGE_LEVELS.SUCCESS %}
          {{ message }}
          <script>
              Swal.fire({
                position: 'center',
                icon: 'success',
                title: 'Sucesso',
                text:'{{ m }}',
                showConfirmButton: true,
                confirmButtonColor: '#000080',
              })
          </script>
      {% endif %}
      {% endfor %}
  </ul>
{% endif %}

{% endblock %}

templates/empresas/menu-perfil-empresa.html
<aside class="col-md-3 mb-3">
  <nav class="list-group">
    <a class="list-group-item" href="{% url 'usuarios:perfil_principal' %}"> Visão geral da conta </a>
    <a class="list-group-item" href="{% url 'empresas:empresa_perfil' %}"> Minha empresa </a>
    <a class="list-group-item" href="{% url 'vitrines:minha_vitrine' %}"> Minha vitrine </a>
    {% if not empresa %}
      <a class="list-group-item" href="#!"> Endereços da empresa </a>
      <a class="list-group-item" href="#!"> Pedidos em espera </a>
      <a class="list-group-item" href="#!"> Minha lista de vendas </a>
      <a class="list-group-item" href="#!"> Meus itens de venda </a>
      <a class="list-group-item" href="#!"> Configurações da empresa </a>
      <a class="list-group-item" href="{% url 'logout' %}"> Sair </a>
    {% else %}
      <a class="list-group-item" href="{% url 'empresas:empresa_endereco' %}"> Endereços da empresa </a>
      <a class="list-group-item" href="#!"> Pedidos em espera </a>
      <a class="list-group-item" href="#!"> Minha lista de vendas </a>
      <a class="list-group-item" href="#!"> Meus itens de venda </a>
      <a class="list-group-item" href="{% url 'empresas:editar_empresa' %}"> Configurações da empresa </a>
      <a class="list-group-item" href="{% url 'logout' %}"> Sair </a>
    {% endif %}
  </nav>
</aside> <!-- col.// -->